### PR TITLE
Create 03-test-plans.md

### PR DESCRIPTION
**Pull request by Samwisebuze**
Here are all my proposed test plans. Please review and mark accept if you think this is good. If not request changes an I can add a few more tests. @Rooknj  I have no clue to test for the front end so I would appreciate your input.

Here is the assignment Description:
For each test case provide the following:
1.  test case identifier (a number or unique name)
2.  purpose of test
3.  description of the test
4.  inputs used for test
5.  expected outputs/results
6.  normal/abnormal/boundary case indication
7.  Blackbox/Whitebox test indication
8.  functional/performance test indication
9.  unit/integration test indication

### CODE REVIEW

**Review by Rooknj — COMMENTED** [review]
Do our test cases need to be more specific or can we get away with being this general?

**Comment by Samwisebuze** [comment]
> Do our test cases need to be more specific or can we get away with being this general?


I looked at some of the examples available and this seems to be descriptive enough. I was descriptive about what is being tested, it doesn't seem like you need to get into the details though. Just describe them enough details so that someone else could implement them. We could be more granular about what to unit test, but I really don't think that is necessary.

**Review by Samwisebuze — COMMENTED** [review]
I think that this all looks good. I'm going to merge this PR.

**Comment by noahbass** [comment]
👍

**Pull request merged**
